name: Momentum Equal Weight Decile Backtest
output-path: results/momentum/quantile/momentum-quantile-equal-monthly.parquet
start: 1963-07-31
end: 2015-12-31
rebalance-frequency: monthly

datasets: 
- crsp
# - ff3
# - crsp_ff3_betas

signal: momentum
n-bins: 10
weighting-scheme: equal

filters:
  - penny-stocks
  - micro-caps
  - null-signal
