name: Momentum Equal Weight Decile Backtest
output-path: results/momentum-test/quantile/momentum-quantile-equal-monthly-test
start: 2000-01-01
end: 2024-12-31
rebalance-frequency: monthly
annualize-results: false

datasets: 
- crsp

signal: momentum
n-bins: 10
weighting-scheme: equal
annualized-results: false

filters:
- low-price-stocks
- null-signal

# - penny-stocks
# - micro-caps
