name: Momentum Equal Weight Decile Backtest
output-path: results/mom/out-of-sample/momentum-out-of-sample-equal
start: 2016-01-01
end: 2024-12-31
rebalance-frequency: monthly
annualize-results: false

datasets: 
- crsp
- ff3
- crsp_ff3_betas

signal: momentum
n-bins: 10
weighting-scheme: equal
annualized-results: false

filters:
- null-idiosyncratic-momentum
- penny-stocks
- micro-caps
- null-signal
