name: Idiosyncratic Momentum Vol Scaled FF3 Equal Weight Decile Backtest
output-path: results/idio-mom-vol-scaled-ff3/quantile/in-sample/idio-mom-vol-scaled-ff3-in-sample-equal
start: 1963-07-31
end: 2015-12-31
rebalance-frequency: monthly
annualized-results: true

datasets: 
- crsp
- ff3
- crsp_ff3_betas

signal: idio_mom_vol_scaled_ff3
n-bins: 10
weighting-scheme: equal

filters:
- penny-stocks
- micro-caps
- null-signal