name: Idiosyncratic Momentum Zero Beta Backtest
output-path: results/idio-mom/mve/select-sample/idio-mom-zero-beta
start: 2000-01-01
end: 2024-12-31
rebalance-frequency: monthly
annualized-results: true

datasets: 
- barra

signal: idio_mom_ff3
alpha-constructor: cross-sectional-z-score
gamma: 2

filters:
- low-price-stocks

constraints:
- zero-beta