name: Momentum Equal Weight Decile Backtest
output-path: results/mom/quantile/in-sample/momentum-in-sample-equal
start: 1963-07-31
end: 2015-12-31
rebalance-frequency: monthly
annualize-results: true

datasets: 
- crsp
- ff3
- crsp_ff3_betas

signal: momentum
n-bins: 10
weighting-scheme: equal

filters:
- null-idiosyncratic-momentum
- penny-stocks
- micro-caps
- null-signal
