name: Momentum Equal Weight Decile Backtest
output-path: results/mom/quantile/select-sample/momentum-select-sample-equal
start: 2000-01-01
end: 2024-12-31
rebalance-frequency: monthly
annualize-results: true

datasets: 
- crsp
- ff3
- crsp_ff3_betas

signal: momentum
n-bins: 10
weighting-scheme: equal

filters:
- null-idiosyncratic-momentum
- penny-stocks
- micro-caps
- null-signal
