name: Momentum Equal Weight Decile Backtest
output-path: results/momentum/quantile/momentum-quantile-equal-monthly
start: 1963-07-31
end: 2015-12-31
rebalance-frequency: monthly
annualize-results: false

datasets: 
- crsp

signal: momentum
n-bins: 10
weighting-scheme: equal
annualized-results: false

filters:
- penny-stocks
- micro-caps
- null-signal
